addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

language: node_js

node_js:
  - 4

os:
  - linux
#  - osx

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9

before_install:
  - npm update -g npm

script:
  - echo "cześć"

deploy:
  provider: npm
  email: bolczyslaw@gmail.com
  api_key: $npmApiKey
  on:
    tags: true
    repo: zaklinaczekodu/babadom